Repository two-yeon/daangn-clone, pull requests merged in 2022-09, with the labels that each got.

#3 Feat: 인증번호 발급 및 비교
  .prettierrc
  package-lock.json
  package.json
  src/app.module.ts
  src/categories/category.entity.ts
  src/dealStates/dealState.entity.ts
  src/posts/post.entity.ts
  src/posts/post.repository.ts
  src/posts/post.resolver.ts
  src/townRanges/townRange.entity.ts
  src/users/model/sms.model.ts
  src/users/user.entity.ts
  src/users/user.module.ts
  src/users/user.repository.ts
  src/users/user.resolver.ts
  src/users/user.service.ts
Labels: feature

#4 Feat: 게시글 신고, 게시글 상태 변경, 게시글 숨김 처리
  package-lock.json
  package.json
  processStates/processState.entity.ts
  src/complaintReasons/complaintReason.entity.ts
  src/configs/typeorm.config.ts
  src/posts/dto/createPostsComplaints.dto.ts
  src/posts/dto/pullUpPostInput.dto.ts
  src/posts/dto/updateDealState.dto.ts
  src/posts/post.entity.ts
  src/posts/post.repository.ts
  src/posts/post.resolver.ts
  src/posts/post.service.ts
  src/posts/postsComplaint.entity.ts
Labels: feature

#5 Feat: user_join_login_jwt
  package-lock.json
  package.json
  src/main.ts
  src/posts/post.entity.ts
  src/posts/post.module.ts
  src/posts/post.repository.ts
  src/posts/post.resolver.ts
  src/posts/post.service.ts
  src/users/dto/joinUser.dto.ts
  src/users/dto/loginUser.dto.ts
  src/users/guards/jwtAuth.guard.ts
  src/users/models/payload.model.ts
  src/users/models/sms.model.ts
  src/users/strategies/jwt.strategy.ts
  src/users/user.entity.ts
  src/users/user.module.ts
  src/users/user.repository.ts
  src/users/user.resolver.ts
  src/users/user.service.ts
  src/users/validations/certified.decorator.ts
  src/users/validations/getUser.decorator.ts
  src/users/validations/inputNumber.pipe.ts
  src/users/validations/phoneNumber.decorator.ts
  src/users/validations/phoneNumber.pipe.ts
Labels: feature

#6 Feat: userName_profileImage_update
  .gitignore
  package-lock.json
  package.json
  src/app.module.ts
  src/posts/dto/searchPost.dto.ts
  src/posts/post.resolver.ts
  src/users/dto/profile.dto.ts
  src/users/models/fileUpload.model.ts
  src/users/user.repository.ts
  src/users/user.resolver.ts
  src/users/user.service.ts
  src/users/validations/getUser.decorator.ts
  src/users/validations/profile.pipe.ts
Labels: feature

#7 Feat: post images upload
  .gitignore
  src/app.module.ts
  src/categories/category.entity.ts
  src/configs/typeorm.config.ts
  src/posts/dto/createPost.dto.ts
  src/posts/dto/searchPost.dto.ts
  src/posts/dto/updatePost.dto.ts
  src/posts/pipes/postImages.pipe.ts
  src/posts/post.entity.ts
  src/posts/post.repository.ts
  src/posts/post.resolver.ts
  src/posts/post.service.ts
  src/posts/postImage.entity.ts
  src/users/user.resolver.ts
  src/users/user.service.ts
Labels: feature

#8 유저 마이페이지 기능
  src/configs/typeorm.config.ts
  src/posts/post.entity.ts
  src/posts/post.repository.ts
  src/posts/post.resolver.ts
  src/posts/post.service.ts
  src/posts/postsLikeRecord.entity.ts
  src/users/dto/follow.dto.ts
  src/users/followings.entity.ts
  src/users/user.entity.ts
  src/users/user.repository.ts
  src/users/user.resolver.ts
  src/users/user.service.ts
Labels: feature

#10 주석 및 파일 이동 관련 수정
  src/app.module.ts
  src/configs/typeorm.config.ts
  src/mypage/dto/follow.dto.ts
  src/mypage/dto/purchaseHistory.dto.ts
  src/mypage/followings.entity.ts
  src/mypage/mypage.module.ts
  src/mypage/mypage.repository.ts
  src/mypage/mypage.resolver.ts
  src/mypage/mypage.service.ts
  src/mypage/purchaseHistory.entity.ts
  src/posts/post.entity.ts
  src/posts/post.repository.ts
  src/posts/post.resolver.ts
  src/posts/post.service.ts
  src/users/dto/follow.dto.ts
  src/users/user.entity.ts
  src/users/user.repository.ts
  src/users/user.resolver.ts
  src/users/user.service.ts
Labels: refactor

#13 Feat: user location
  package-lock.json
  package.json
  src/configs/typeorm.config.ts
  src/posts/post.entity.ts
  src/posts/post.repository.ts
  src/posts/post.resolver.ts
  src/posts/post.service.ts
  src/townRanges/townRange.entity.ts
  src/users/dto/deleteTown.dto.ts
  src/users/dto/mylocation.dto.ts
  src/users/dto/profile.dto.ts
  src/users/location.entity.ts
  src/users/user.entity.ts
  src/users/user.module.ts
  src/users/user.repository.ts
  src/users/user.resolver.ts
  src/users/user.service.ts
  src/users/validations/profile.pipe.ts
  행정_법정동_중심좌표.csv
Labels: feature

#14 마이페이지 주석 수정 및 게시글 좋아요 & 조회수 기능 트랜잭션 수정
  src/mypage/mypage.service.ts
  src/posts/post.repository.ts
Labels: refactor

#15 Feat: town range
  package-lock.json
  package.json
  src/posts/dto/createPost.dto.ts
  src/posts/dto/searchPost.dto.ts
  src/posts/pipes/postImages.pipe.ts
  src/posts/post.entity.ts
  src/posts/post.module.ts
  src/posts/post.repository.ts
  src/posts/post.resolver.ts
  src/posts/post.service.ts
  src/townRanges/townRange.entity.ts
  src/users/guards/jwtAuth.guard.ts
  src/users/location.entity.ts
  src/users/strategies/jwt.strategy.ts
  src/users/user.module.ts
  src/users/user.resolver.ts
  src/users/user.service.ts
  src/users/validations/certified.decorator.ts
  src/users/validations/getUser.decorator.ts
  src/users/validations/inputNumber.pipe.ts
  src/users/validations/phoneNumber.decorator.ts
  src/users/validations/phoneNumber.pipe.ts
  src/users/validations/profile.pipe.ts
Labels: feature

#16 Feat: image upload to s3
  package-lock.json
  package.json
  src/posts/post.repository.ts
  src/posts/post.service.ts
  src/users/models/fileUpload.model.ts
  src/users/user.repository.ts
  src/users/user.service.ts
Labels: feature

#17 채팅 기능 (소켓 적용 x)
  package-lock.json
  package.json
  src/chats/chat.entity.ts
  src/chats/chat.gateway.ts
  src/chats/chat.module.ts
  src/chats/chat.repository.ts
  src/chats/chat.resolver.ts
  src/chats/chat.service.ts
  src/chats/chatRoom.entity.ts
  src/chats/dto/createChat.dto.ts
  src/chats/dto/createChatRoom.dto.ts
  src/configs/typeorm.config.ts
  src/posts/post.entity.ts
  src/users/user.entity.ts
Labels: feature

#18 Feat: review
  src/app.module.ts
  src/configs/typeorm.config.ts
  src/posts/dto/searchPost.dto.ts
  src/posts/post.entity.ts
  src/posts/post.module.ts
  src/posts/post.resolver.ts
  src/posts/post.service.ts
  src/reviews/dto/review.dto.ts
  src/reviews/entities/buyerReview.entity.ts
  src/reviews/entities/mannerItem.entity.ts
  src/reviews/entities/scoreItem.entity.ts
  src/reviews/entities/selectedMannerItemToBuyer.entity.ts
  src/reviews/entities/selectedMannerItemToSeller.entity.ts
  src/reviews/entities/sellerReview.entity.ts
  src/reviews/pipes/review.pipe.ts
  src/reviews/review.module.ts
  src/reviews/review.repository.ts
  src/reviews/review.resolver.ts
  src/reviews/review.service.ts
Labels: feature

#19 Feat/admin setting
  src/admins/admin.module.ts
  src/admins/admin.repository.ts
  src/admins/admin.resolver.ts
  src/admins/admin.service.ts
  src/admins/dto/createAdmin.dto.ts
  src/admins/dto/updateAdmin.dto.ts
  src/admins/entities/admin.entity.ts
  src/app.module.ts
  src/configs/typeorm.config.ts
Labels: feature

#20 Feat: admin account
  package-lock.json
  package.json
  src/admins/admin.module.ts
  src/admins/admin.repository.ts
  src/admins/admin.resolver.ts
  src/admins/admin.service.ts
  src/admins/decorators/getAdmin.decorator.ts
  src/admins/decorators/role.decorator.ts
  src/admins/dto/admin.dto.ts
  src/admins/dto/createAdmin.dto.ts
  src/admins/dto/loginAdmin.dto.ts
  src/admins/dto/updateAdmin.dto.ts
  src/admins/entities/admin.entity.ts
  src/admins/entities/adminAuthority.entity.ts
  src/admins/guards/jwtAuth.guard.ts
  src/admins/guards/roles.guard.ts
  src/admins/models/payload.model.ts
  src/admins/models/role.enum.ts
  src/admins/pipes/authority.pipe.ts
  src/admins/repositories/admin.repository.ts
  src/admins/repositories/adminAuthority.repository.ts
  src/admins/strategies/jwt.strategy.ts
  src/configs/typeorm.config.ts
  src/posts/post.service.ts
  src/reviews/pipes/review.pipe.ts
  src/reviews/review.service.ts
  src/users/user.service.ts
Labels: feature

#22 Feat: 채팅 신고기능 추가
  src/chats/chat.entity.ts
  src/chats/chat.module.ts
  src/chats/chat.repository.ts
  src/chats/chat.resolver.ts
  src/chats/chat.service.ts
  src/chats/chatComplaints.entity.ts
  src/chats/dto/createChatComplaints.dto.ts
  src/chats/dto/createUsersComplaints.dto.ts
  src/chats/userComplaints.entity.ts
Labels: feature

#23 Refactor: admin jwt
  src/admins/admin.service.ts
  src/admins/decorators/role.decorator.ts
  src/admins/guards/jwtAuth.guard.ts
  src/admins/guards/roles.guard.ts
  src/admins/strategies/jwt.strategy.ts
  src/users/user.service.ts
Labels: refactor

#25 Fix: admin, user jwt 에러 해결
  src/admins/admin.service.ts
  src/admins/decorators/role.decorator.ts
  src/admins/guards/jwtAuth.guard.ts
  src/admins/guards/roles.guard.ts
  src/admins/strategies/jwt.strategy.ts
  src/users/user.service.ts
Labels: Fix

#26 채팅 기능 전체적인 수정
  src/chats/blockUser.entity.ts
  src/chats/chat.repository.ts
  src/chats/chat.resolver.ts
  src/chats/chat.service.ts
  src/chats/chatComplaints.entity.ts
  src/chats/chatRoom.entity.ts
  src/chats/dto/createBlockUser.dto.ts
  src/chats/dto/createChatComplaints.dto.ts
  src/chats/userComplaints.entity.ts
  src/complaintReasons/complaintReason.entity.ts
  src/configs/typeorm.config.ts
  src/posts/postsComplaint.entity.ts
  src/processStates/processState.entity.ts
  src/users/user.entity.ts
Labels: Fix

#27 Feat: admin search post complaint
  src/admins/admin.module.ts
  src/admins/admin.resolver.ts
  src/admins/admin.service.ts
  src/admins/dto/searchPostComplaint.dto.ts
  src/complaintReasons/complaintReason.entity.ts
  src/configs/typeorm.config.ts
  src/posts/post.entity.ts
  src/posts/post.module.ts
  src/posts/post.resolver.ts
  src/posts/post.service.ts
  src/posts/postComplaints.entity.ts
  src/posts/repositories/post.repository.ts
  src/posts/repositories/postComplaint.repository.ts
  src/processStates/processState.entity.ts
Labels: feature

#28 게시글, 채팅, 유저 신고 processState 기본값 1로 수정 및 컬럼명 수정 & 마이페이지 구매 처리 트랜잭션 추가
  src/app.module.ts
  src/chats/chat.module.ts
  src/chats/chat.service.ts
  src/chats/chatComplaints.entity.ts
  src/chats/repositories/chat.repository.ts
  src/chats/userComplaints.entity.ts
  src/mypage/mypage.repository.ts
  src/mypage/mypage.resolver.ts
  src/mypage/mypage.service.ts
  src/posts/dto/createPostsComplaints.dto.ts
  src/posts/post.resolver.ts
  src/posts/post.service.ts
  src/posts/postComplaints.entity.ts
  src/posts/repositories/post.repository.ts
  src/posts/repositories/postComplaint.repository.ts
  src/users/user.entity.ts
Labels: feature, refactor

#29 Feat: admin search complaint
  src/admins/admin.module.ts
  src/admins/admin.resolver.ts
  src/admins/admin.service.ts
  src/admins/dto/searchComplaint.dto.ts
  src/admins/guards/jwtAdminAuth.guard.ts
  src/chats/chatComplaints.entity.ts
  src/chats/repositories/chatComplaints.repository.ts
  src/chats/repositories/userComplaints.repository.ts
  src/chats/userComplaints.entity.ts
  src/posts/repositories/postComplaint.repository.ts
Labels: feature
