Repository two-yeon/daangn-clone, pull requests merged in 2022-10, with the labels that each got.

#32 Docs: update README.md
  README.md
Labels: documentation

#33 관리자 신고 처리 기능 및 로그 기능
  src/admins/admin.module.ts
  src/admins/admin.resolver.ts
  src/admins/admin.service.ts
  src/admins/dto/searchWorkLogs.dto.ts
  src/admins/entities/admin.entity.ts
  src/admins/entities/processTypes.entity.ts
  src/admins/entities/workLogs.entity.ts
  src/admins/entities/workTypes.entity.ts
  src/admins/repositories/adminWorkLogs.repository.ts
  src/chats/chat.service.ts
  src/chats/repositories/chatComplaints.repository.ts
  src/chats/repositories/userComplaints.repository.ts
  src/configs/typeorm.config.ts
  src/mypage/mypage.resolver.ts
  src/mypage/mypage.service.ts
  src/mypage/repositories/mypage.repository.ts
  src/posts/entities/postsLikeRecord.entity.ts
  src/posts/entities/postsViewRecord.entity.ts
  src/posts/entities/priceOffer.entity.ts
  src/posts/repositories/postComplaint.repository.ts
  src/users/repositories/user.repository.ts
Labels: feature

#34 Refactor/code refactoring2
  .gitignore
  schema.gql
  src/admins/admin.resolver.ts
  src/admins/admin.service.ts
  src/admins/decorators/getAdmin.decorator.ts
  src/admins/entities/workLogs.entity.ts
  src/chats/chat.gateway.ts
  src/chats/chat.service.ts
  src/posts/post.service.ts
  src/posts/repositories/post.repository.ts
  src/users/user.service.ts
Labels: refactor

#35 dev to main
  .gitignore
  schema.gql
  src/admins/admin.module.ts
  src/admins/admin.resolver.ts
  src/admins/admin.service.ts
  src/admins/decorators/getAdmin.decorator.ts
  src/admins/dto/searchWorkLogs.dto.ts
  src/admins/entities/admin.entity.ts
  src/admins/entities/processTypes.entity.ts
  src/admins/entities/workLogs.entity.ts
  src/admins/entities/workTypes.entity.ts
  src/admins/repositories/adminWorkLogs.repository.ts
  src/chats/chat.gateway.ts
  src/chats/chat.service.ts
  src/chats/repositories/chatComplaints.repository.ts
  src/chats/repositories/userComplaints.repository.ts
  src/configs/typeorm.config.ts
  src/mypage/mypage.resolver.ts
  src/mypage/mypage.service.ts
  src/mypage/repositories/mypage.repository.ts
  src/posts/entities/postsLikeRecord.entity.ts
  src/posts/entities/postsViewRecord.entity.ts
  src/posts/entities/priceOffer.entity.ts
  src/posts/post.service.ts
  src/posts/repositories/post.repository.ts
  src/posts/repositories/postComplaint.repository.ts
  src/users/repositories/user.repository.ts
  src/users/user.service.ts
Labels: refactor
